controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    methods: ['POST']

payment_create_intent:
    path: /api/create-payment-intent
    controller: 'App\Controller\PaymentController::createPaymentIntent'
    methods: ['POST']

payment_confirm:
    path: /api/confirm-payment
    controller: 'App\Controller\PaymentController::confirmPayment'
    methods: ['POST']

customer_commands_view:
    path: '/customer/{customerId}/commands'
    controller: 'App\Controller\CustomerCommandsController::viewCommands'